imports:
    - { resource: easyadmin/ }

easy_admin:
    design:
        menu:
            -
                label: 'menu.krg_user'
                priority: 5
                children:
                    - { entity: 'User', icon: 'users', label: 'menu.user' }
