imports:
  - { resource: easyadmin/ }

easy_admin:
  design:
    menu:
      -
        label: 'Security'
        priority: 1
        children:
            - { entity: 'User', icon: 'users', label: 'Users' }
