services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $firewallName: 'main'

    KRG\UserBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    KRG\UserBundle\Form\Type\:
        resource: '../../Form/Type'
        public: true
        tags: ['form.type']

    KRG\UserBundle\EventSubscriber\:
        resource: '../../EventSubscriber'
        tags: ['kernel.event_subscriber']

    KRG\UserBundle\Entity\Listener\UserListener:
        tags: ['doctrine.event_subscriber']

    KRG\UserBundle\Annotation\Listener\PrivateDataListener:
        tags: [{ name: 'doctrine.event_listener', event: 'preSoftDelete' }]

    KRG\UserBundle\Util\:
        resource: '../../Util'
        public: true

    KRG\UserBundle\Manager\:
        resource: '../../Manager'
        public: true

    KRG\UserBundle\Security\:
        resource: '../../Security'
        public: true

    KRG\UserBundle\Message\:
        resource: '../../Message'
        lazy: true
        tags: ['message.type']

    KRG\UserBundle\Validator\:
        resource: '../../Validator'
        public: true

    # Alias https://symfony.com/doc/current/service_container/alias_private.html
    security.authentication.success_handler.main.form_login:
        alias: KRG\UserBundle\Security\Firewall\AuthenticationSuccessHandler

    # Interfaces https://symfony.com/doc/current/service_container/autowiring.html#using-aliases-to-enable-autowiring
    KRG\UserBundle\Manager\LoginManagerInterface: '@KRG\UserBundle\Manager\LoginManager'
    KRG\UserBundle\Manager\UserManagerInterface: '@KRG\UserBundle\Manager\UserManager'
    KRG\UserBundle\Util\PasswordUpdaterInterface: '@KRG\UserBundle\Util\PasswordUpdater'
    Symfony\Component\Security\Http\Authentication\AuthenticationSuccessHandlerInterface: '@KRG\UserBundle\Security\Firewall\AuthenticationSuccessHandler'

    # Deprecated
    Symfony\Component\Security\Http\HttpUtils:
        alias: security.http_utils
    Symfony\Component\Security\Http\Session\SessionAuthenticationStrategyInterface:
        alias: security.authentication.session_strategy

    fos_user.user_manager:
        alias: '@KRG\UserBundle\Manager\UserManager'

    fos_user.util.token_generator:
        alias: '@KRG\UserBundle\Util\TokenGenerator'
