easy_admin:
    entities:
        User:
            class: '%krg_cms.user.class%'
            list:
                title:  '<i class="fa fa-users-large"></i> User'
                fields:
                    -
                        property: 'enabled'
                    -
                        property: 'email'
                    -
                        property: 'firstname'
                    -
                        property: 'lastname'
                    -
                        property: 'createdAt'
                        label: 'Registered at'
                    -
                        property: 'lastLogin'
            edit:
                fields:
                    - { property: 'enabled' }
                    - { property: 'email' }
                    - { property: 'firstname' }
                    - { property: 'lastname' }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    - { property: 'enabled' }
                    - { property: 'email' }
                    - { property: 'firstname' }
                    - { property: 'lastname' }
                    - { property: 'plainPassword', type: 'text', 'label': 'Password', type_options: { required: true } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }
                form_options: { validation_groups: ['Registration'] }
