easy_admin:
    entities:
        User:
            class: 'KRG\UserBundle\Entity\UserInterface'
            controller: 'KRG\UserBundle\Controller\AdminController'
            list:
                actions:
                    - { name: 'switch', icon: 'user-secret', css_class: 'btn btn-secondary', route: 'krg_user_admin_switch', roles: ['ROLE_ALLOWED_TO_SWITCH'], menu_dropdown: true }
                fields: ['email', 'firstname', 'lastname', 'createdAt', 'lastLogin', 'enabled']
            edit:
                fields: ['email', 'firstname', 'lastname', 'roles', 'enabled']
                form_options: { validation_groups: ['Registration'] }
            new:
                fields: ['email', 'firstname', 'lastname', 'roles', 'enabled']
                form_options: { validation_groups: ['Registration'] }
